export const Data = [
  {
    id: 1,
    name: "sarileru nekkevaru",
    src: "",
    actor: "mahesh babu",
    director: "anil ravipuri",
    producer: "def",
    year: "2019",
    rating_array: [],
    rating: 0
  },
  {
    id: 2,
    name: "asdfghj asdfghj",
    src: "",
    actor: "prabhas",
    director: "kjhgfd dfghj",
    producer: "def",
    year: "2019",
    rating_array: [],
    rating: 0
  },
  {
    id: 3,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 4,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 5,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 6,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 7,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 8,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 9,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 10,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 11,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 12,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 13,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 14,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 15,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    rating_array: [],
    year: "2017",
    rating: 0
  },
  {
    id: 16,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    rating_array: [],
    year: "2017",
    rating: 0
  },
  {
    id: 17,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    year: "2017",
    rating_array: [],
    rating: 0
  },
  {
    id: 18,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    rating_array: [],
    year: "2017",
    rating: 0
  },
  {
    id: 19,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    rating_array: [],
    year: "2017",
    rating: 0
  },
  {
    id: 20,
    name: "wertjklpoiu errt",
    src: '',
    actor: "nayak",
    director: "opkli",
    producer: "bbyu",
    rating_array: [],
    year: "2017",
    rating: 0
  }]